dbconnection:
    host: localhost
    port: 5432
    password: password
    username: username
    dbname: dbname
    driver-name: postgres

server:
    host: localhost
    port: 8080
    templates: '/home/pavelpal/projects/go-projects/TP-lab-2/resources/static/templates/'

    
    