version: '3.9'

services:
  shop:
    build: ./
    command: ./wait-for-postgres.sh db ./main -config resources/config/docker-app-confit.yaml
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=golang_db
    ports:
      - "5438:5432"
